feat: fix invoke add-github-enterprise-repository
Calling the 'invoke add-github-enterprise-repository' in a new
project which has no addons configured in its addons.yaml
throws the NoneType error below

TypeError: argument of type 'NoneType' is not iterable